#+TITLE: Are MLPs all you need for computer vision?
#+SUBTITLE: Final Project for Intro to Computational Intelligence in Fall 2021
#+BEAMER_THEME: metropolis
#+BEAMER_HEADER: \usepackage{tikz}
#+BEAMER_HEADER: \author{Alex Morehead}
#+BEAMER_HEADER: \institute{\includegraphics[width=2.8cm]{MU_Eps.png}}
#+OPTIONS: toc:nil
#+LATEX_CMD: xetex

#+BEAMER_HEADER: \addtobeamertemplate{title page}{}{%
#+BEAMER_HEADER: \begin{tikzpicture}[remember picture,overlay]
#+BEAMER_HEADER: \node[anchor=north east,yshift=2pt] at (current page.north east) {\includegraphics[height=0.9cm]{UM.png}};
#+BEAMER_HEADER: \end{tikzpicture}}

#+BEAMER_HEADER: \addtobeamertemplate{frametitle}{}{%
#+BEAMER_HEADER: \begin{tikzpicture}[remember picture,overlay]
#+BEAMER_HEADER: \node[anchor=north east,yshift=2pt] at (current page.north east) {\includegraphics[height=0.8cm]{UM.png}};
#+BEAMER_HEADER: \end{tikzpicture}}
#+OPTIONS: H:2 toc:t
\newpage

* Abstract
Convolutional Neural Networks (CNNs) are to date a standard class of deep
learning algorithms for learning from image-like data
cite:albawi2017understanding. Recently, alternative types of neural networks
such as Attentive CNNs cite:neumann2017attentive, Vision Transformers
cite:han2020survey, and MLP-Mixers cite:tolstikhin2021mlp have been proposed for
tasks in computer vision. Interestingly, MLP-Mixers have been succinctly
designed to simultaneously incorporate the advantages of multilayer perceptrons
(MLPs), CNNs, and Transformers (i.e., per-location features and patch-based
spatial information) for image-based deep learning. However, there are currently
few explorations in the literature on comparing these new MLP vision models to
their standard MLP and shared weight neural network (SWNN) counterparts. In this
work, I propose to investigate the effect of the location and patch-based
feature mixing techniques that MLP-Mixers apply to see their effect on the
model's image classification performance. My study will make use of benchmark
computer vision datasets such as the MNIST and ImageNet datasets to allow
meaningful comparisons of the classification results presented by the MLP-Mixer
with those offered by standard MLPs and SWNNs.
* Introduction
** Motivation
Over the last few years, a litany of new neural network architectures have
recently been proposed for computer vision tasks. Lagging behind these new
models, however, are thorough case studies examining their relationship to
historically-grounded neural networks such as MLPs and CNNs. Conducting more of
such case studies could lead to an enhanced understanding of the true amount of
progress that has been made in image-based deep learning.

* Conclusion
Through this project, we will see that MLP Mixers achieve impressive results for
image classification by distilling the advantages of contemporary computer
vision learning algorithms such as CNNs and Transformers into a single simple
network.
\newpage
* References
:PROPERTIES:
:BEAMER_OPT: fragile,allowframebreaks,label=
:END:
bibliographystyle:unsrt
bibliography:../../../../../../../Bibliographies/mindmeld.bib
