wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: train_acc
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    python_version: 3.9.0
    start_time: 1637466459
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      3:
      - 7
      4: 3.9.0
      5: 0.12.7
      8:
      - 5
c_hidden:
  desc: null
  value: 16
c_in:
  desc: null
  value: 1
c_out:
  desc: null
  value: 10
dp_rate:
  desc: null
  value: 0.1
num_layers:
  desc: null
  value: 2
